CXX = g++

TARGET = prueba.out

SRCS = src/Bloque.cpp \
       src/CargarFiguras.cpp \
       src/Figura.cpp \
       src/SistemaArchivos.cpp \
       src/prueba.cpp

all:
	$(CXX) $(SRCS) -Iinclude -o $(TARGET)

clean:
	rm -f $(TARGET)